# -*- coding: utf-8 -*-
"""data_processing_functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_QSSX6hyRVHTC7cGw6Ny5sbR_9tf5ns8
"""
import os

def combine_txt(files,outpath,out_file_name):
  path_file=outpath+out_file_name
  if not os.path.isfile(path_file):
    # Read all the files in netflix and store them in one big file
    # We re reading from each of the four files and appendig each rating to a global file 'train.csv'
    data = open(path_file, mode='a')
    
    row = list()
    for file in files:
        print("Reading ratings from {}...".format(file))
        with open(file) as f:
            for line in f: 
                del row[:] # you don't have to do this.
                line = line.strip()
                if line.endswith(':'):
                    # All below are ratings for this movie, until another movie appears.
                    movie_id = line.replace(':', '')
                else:
                    row = [x for x in line.split(',')]
                    row.insert(0, movie_id)
                    data.write(','.join(row))
                    data.write('\n')
        print("Done.\n")
    print("Combined data ",out_file_name," saved in ",outpath)
    data.close()
    
    
